
services:
  backend:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
  frontend:
    build: frontend
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/app
